### ISSUE TITLE
Monitoring MySQL database for specific column is not working

### ISSUE THREAD

**Issue by nrupen92** [spencerlambert/mysql-events#12]
I have been using MySQL database to monitor specific column of table. It does not capture any changes that happens in the database.
My Code :

var eventObj = conObj.add(data.monitor_path, function(oldData, newData) {
	console.log(oldData);
        console.log(newData);

	}, 'Active');

can you please let me know what i am missing.?

Thanks.

**Comment by spencerlambert** [comment]
What is data.monitor_path set to?

**Comment by cikupin** [comment]
yeah, it's not working in my code too. 
This is my code:


var watcher = MysqlEventWatcher.add('realtime_chart.chart_data', function(oldRow, newRow) {
    if(oldRow === null) {
        console.log(oldRow);
    }

    if(oldRow !== null && newRow !== null) {
        console.log(oldRow);
        console.log(newRow);
    }
});

Where:
1. **realtime_chart** is my database
2. **chart_data** is my table

Do you have any ide why it doesn't work ??

**Comment by spencerlambert** [comment]
Is your database user setup as a replication user, and do you have binary logging turned on?

**Comment by cikupin** [comment]
my bad. I add replication user and now it's working. thank you @spencerlambert

**Comment by nrupenku** [comment]
my bad...i didnt add replication user. Its working now.

**Comment by happilymarrieddad** [comment]
@spencerlambert hey man when you say REPLICATION USER what do you mean? I can't seem to get this to work either but like the others everything else works great.

**Comment by spencerlambert** [comment]
@happilymarrieddad 

This: https://dev.mysql.com/doc/refman/5.7/en/replication-howto-repuser.html

**Comment by happilymarrieddad** [comment]
@spencerlambert do you know why it works at the table level but not the column level?

**Comment by happilymarrieddad** [comment]
@spencerlambert  I dropped the user and copied and pasted the one from the link you posted and it's still not working. It said I needed to add REPLICATION CLIENT so I did that and it's still not working. It works great for tables. Is there anything else I need to do?

**Comment by spencerlambert** [comment]
@happilymarrieddad in order for the column level to match anything, you need to include the last arg on the `add()`, which is ether a regex or string to do a perfect match on.

**Comment by happilymarrieddad** [comment]
@spencerlambert is there a way to get any change on that column? For example if I wanted to watch ```orders.status_id``` on the ```fusion``` database could I do this?

```
var watcher = mysqlEventWatcher.add(
			'fusion.orders.status_id',
			function(oldRow,newRow,event) {
				console.log(oldRow)
				console.log(newRow)
				console.log(event)
			},
			'(.*?)'
		)
```

**Comment by spencerlambert** [comment]
@happilymarrieddad Your example code is using a `string` and not a javascript `regex` as the third arg.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

`/./` would match everything, but and empty or null value.

**Comment by happilymarrieddad** [comment]
I decided to go another route. I'm just going to watch the whole table. I tried the regexp thing and that wasn't working either. No worries man. I need to watch a bunch of fields on a table. Thanks for your time man!
