### ISSUE TITLE
Nothing's happening...

### ISSUE THREAD

**Issue by bennetgallein** [spencerlambert/mysql-events#13]
I'm using zwamp for coding on the move and it has normal mysql.
I don't get any error in the console..

my code 
```javascript
var dsn = {
    host: 'localhost',
    user: 'root',
    password: '',
};
var mysqlEventWatcher = mysqlevents(dsn);
var watcher = mysqlEventWatcher.add(
  'skinpay.payments',
  function (oldRow, newRow) {
      //row inserted
    console.log("New row inserted!");
    if (oldRow === null) {
      //insert code goes here 
    }
 
     //row deleted 
    if (newRow === null) {
      //delete code goes here 
    }
 
     //row updated 
    if (oldRow !== null && newRow !== null) {
      //update code goes here 
    }
  }, 
  'match this string or regex'
);
```
It should print something in the console if I insert something manually, right?

Looking for quick help.

**Comment by spencerlambert** [comment]
Do you have mysql biniary logging turned on and does the mysql user have replication privileges?  I would recommend using a different user besides root.

https://dev.mysql.com/doc/refman/5.7/en/replication-howto-repuser.html

**Comment by bennetgallein** [comment]
I'm gonna try that tomorrow... Thanks for the fast response. :)

**Comment by bennetgallein** [comment]
Okay, so I added a new user following the instructions you send in your post.. But nothing's happening.. It should probably work with my root account, because it has all permissions, right? Here's my MySQL config and a Screenshot of the Users permissions.

[my.txt](https://github.com/spencerlambert/mysql-events/files/478190/my.txt)
https://gyazo.com/ea0ae782c880ee056de7fad851a0f817

**Comment by spencerlambert** [comment]
Is MySQL Binary Logging turned on?

**Comment by spencerlambert** [comment]
Also, remove the last argument from your code, or updated it to something you want to match on.

> 'match this string or regex'

**Comment by bennetgallein** [comment]
What should go in there? I want to listen if any new row gets inserted.. I don't want it to have any special value..

**Comment by spencerlambert** [comment]
Then just remove the argument completely.

**Comment by bennetgallein** [comment]
Okay, so I removed it now.. But still after inserting something manually nothing appears in the console..

**Comment by spencerlambert** [comment]
Then it's likely binary logs aren't turned on.

**Comment by bennetgallein** [comment]
But I dont get the error that it's not turned on.. But I should if it isn't right?

**Comment by spencerlambert** [comment]
If you don't know that binary logging is turned on, then you need to confirm that it is.  I'm not sure how  to configure binary logging with ZWAMP.

**Comment by bennetgallein** [comment]
Okay.. I didn't changed anything but magicly seems to work.. Thanks for the great support anyways.. :)
