### ISSUE TITLE
Not working with multiple application with.

### ISSUE THREAD

**Issue by sctaix** [spencerlambert/mysql-events#25]
Hi,

I have two applications with nodejs, actually version 1 and version 2.

When I start two applications at the same time, the mysql-evetns not working properly.

I created database replication user for each applications for event watching, but event logs wrote only one of application.

Is it possible that run multiple applications for mysql-events at the same time?

**Comment by spencerlambert** [comment]
MySQL replication works between multiple slaves, so I see no reason why `mysql-events` couldn't work on two instances.
