### ISSUE TITLE
Error in list of changedColumns (for columns of type datetime) in update

### ISSUE THREAD

**Issue by fahedmonzer** [spencerlambert/mysql-events#36]
if the obj1 = obj2, the comparison (obj1 != obj2) return true in JS

and because the code return column(of type datetime) as object
 **typeof(row.fields.column) === "object"** , and we have a problem in comparison
it's add the column name (of type datetime) to changedColumns

you can solve this issue by checking the type of column before comparison  or convert object to string

example add before :
https://github.com/spencerlambert/mysql-events/blob/master/index.js#L162
this code :
**if(typeof(row.before[key]) === "object") row.before[key] = JSON.stringify(row.before[key]);**
**if(typeof(row.after[key]) === "object") row.after[key] = JSON.stringify(row.after[key]);**

you can read this :
https://stackoverflow.com/questions/1068834/object-comparison-in-javascript

thank you

**Comment by spencerlambert** [comment]
Would you mind submitting a pull request for this fix?

**Comment by fahedmonzer** [comment]
yes 👍
