### ISSUE TITLE
Events are not triggering if the database having period symbol (.)

### ISSUE THREAD

**Issue by jmhemadri** [spencerlambert/mysql-events#42]
HI All,

I am having database name called "employee.qa" and when I used table like below to monitor and it is not trigger.

var category_table = 'employee.qa.tablename';
var category = mysqlEventWatcher.add(
category_table,
  function (oldRow, newRow, event) {
  console.log("Category Event Watcher Called ");

-----

---

But the above code working fine if i use database employee_qa. Can you please let me know is there any work around with period symbol. I tried below ways
var category_table = 'employee.qa.tablename';
var category_table = '[employee.qa].tablename';
var category_table = ''employee.qa'.tablename';
var category_table = '\'employee.qa\'.tablename';

Thanks in advance

**Comment by a-k-macdonald** [comment]
I don't know if you can but did you try `employee.qa`.`tablename`.

I'm not sure it will help but it might.

**Comment by spencerlambert** [comment]
It's the dot within the database name that isn't compatible with this code.  Dots are used as delimiters between database, table, column, and regex.  The parsing code would have to change.

I think using a dot within a database name is kinda confusing anyway, as a dot between a database and table is standard MySQL syntax.  So it's kinda hard to quickly understand what "employee.qa" means, is it a database or is it a database and table.

**Comment by jmhemadri** [comment]
Understood. It there any workaround like if we pass database with in brackets like [employee.qa]?

**Comment by spencerlambert** [comment]
In looking at my code more (sorry it's been a while sense I wrote this), I see that it doesn't actually parse the `watch on` var.  It joins is to match on a `watch on`, so this dot thing is coming from something else, like may be ZongJi.

Maybe ZongJi is converting your `.` to an `_`.  I guess use `emplyoee_qa` and be happy.

**Comment by jmhemadri** [comment]
Okay Thank you so much will change my database.
