### ISSUE TITLE
Fields changing order

### ISSUE THREAD

**Issue by olehumborstad** [spencerlambert/mysql-events#47]
The fields (RecNum, TmStamp) in my newRow object just changed order,
Used to be:
  fields: 
   { RecNum: 36290117,
     TmStamp: 2019-03-29T13:01:09.000Z,
     VH_mps: 1.5679999589920044,
     VR_grader: 199 }
Now it has the timestamp in the RecNum instead:
  fields: 
   { RecNum: 2019-03-29T13:01:09.000Z,
     TmStamp: 36290117,
     VH_mps: 1.5679999589920044,
     VR_grader: 199 }

The new rows in the database is as they should be, the code is as the readme describes. My application doesn't work now, I can't just rewrite RecNum being the DATETIME. What if it goes back?  Any idea what happend here or how to fix this?

**Comment by spencerlambert** [comment]
This isn't an issue with this code.  Might be a change in the config in your MySQL server set up.  This code doesn't order fields period.
