### ISSUE TITLE
Listening to a specific column

### ISSUE THREAD

**Issue by Arakiri** [spencerlambert/mysql-events#7]
Hello,

I try to listen a specific column but I can't manage to make it work. It works fine when I only listen to a database or a table, tough. Here is my code :

`var MySQLEvents = require('mysql-events');
var dsn = {
    host:      'localhost',
    user:      '****',
    password:  '****',
};
var mysqlEventWatcher = MySQLEvents(dsn);

//Fires when a match is started
var newMatchStarted =mysqlEventWatcher.add(
    'bot.matchs.status',
    function (oldRow, newRow) {
        console.log(newRow);
        console.log(oldRow);
    }
);`

Thanks a lot!

**Comment by spencerlambert** [comment]
For columns, the current code only support value matches.  Add the 
"value" tag and a third argument, like:

var event1 = myCon.add(
'dbName.tableName.fieldName.value',
function(oldRow, newRow) {
     //code goes here
},
'Active'
);

The third arg can also be a regex.

Thanks,
Spence

**Comment by Arakiri** [comment]
Thanks for the quick reply, nevetheless it doesn't seems to work neither
